name: Update Notification
on:
  push:
    branches:
      - main

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification
        env:
          TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          MSG: ${{ github.event.head_commit.message }}
        run: |
          curl -s -X POST "https://api.telegram.org/bot$TOKEN/sendMessage" \
          --data-urlencode "chat_id=$CHAT_ID" \
          --data-urlencode "text=🔔 تم تحديث المنظومة بنجاح.
          
          📝 التعديلات الجديدة:
          $MSG"
