name: Update Notification
on:
  push:
    branches:
      - main

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Send Arabic Notification
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
          -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d "text=🔔 تم تحديث المنظومة بنجاح.%0A%0A📝 التعديلات الجديدة:%0A${{ github.event.head_commit.message }}"
